(function(g){var window=this;var Txa=function(a,b){return g.Kb(a,b)},Z5=function(a,b,c){a.A.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.C)()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.an(a.A,b,c)},Uxa=function(a,b){var c=[];
g.jk(b,function(d){try{var e=g.co.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.bo(e)&&c.push(d)},a);
return c},Vxa=function(a,b){var c=Uxa(a,b);
(0,g.y)(c,function(d){g.co.prototype.remove.call(this,d)},a)},Wxa=function(a){if(a.Xc){if(a.Xc.locationOverrideToken)return{locationOverrideToken:a.Xc.locationOverrideToken};
if(null!=a.Xc.latitudeE7&&null!=a.Xc.longitudeE7)return{latitudeE7:a.Xc.latitudeE7,longitudeE7:a.Xc.longitudeE7}}return null},Xxa=function(a,b){g.eb(a,b)||a.push(b)},b6=function(a){var b=0,c;
for(c in a)b++;return b},Yxa=function(a,b){var c=b instanceof g.yc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},c6=function(){},Zxa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},$xa=function(a){if(a.Sd&&"function"==typeof a.Sd)return a.Sd();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Gb(a)},aya=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Pe&&"function"==typeof a.Pe)var c=a.Pe();else if(a.Sd&&"function"==typeof a.Sd)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Hb(a);d=$xa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},bya=function(a,b,c,d){var e=new g.Pm(null,void 0);
a&&g.Qm(e,a);b&&g.Rm(e,b);c&&g.Sm(e,c);d&&(e.u=d);return e},d6=function(a,b){g.Po[a]=!0;
var c=g.No();c&&c.publish.apply(c,arguments);g.Po[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Mm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",cya(this,a.capabilities||""),dya(this,a.experiments||""))},cya=function(a,b){a.capabilities.clear();
(0,g.ze)(b.split(","),g.Ra(Txa,eya)).forEach(function(c){a.capabilities.add(c)})},dya=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},fya=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},gya=function(a){return new f6(a)},hya=function(a){return Array.isArray(a)?(0,g.Ic)(a,gya):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return Array.isArray(a)?"["+(0,g.Ic)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},iya=function(a){return(0,g.Ic)(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.bb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.bb(a,function(c){return g6(c,b)})},jya=function(){var a=(0,g.Rs)();
a&&Vxa(a,a.o.Hg(!0))},m6=function(){var a=g.Us("yt-remote-connected-devices")||[];
g.vb(a);return a},kya=function(a){if(g.fb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},lya=function(a){g.Ts("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Us("yt-remote-device-id");a||(a=j6(),g.Ts("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.eb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.eb(a,b);g.Ws()&&g.yb(a,b);a=kya(a);if(g.fb(a))try{g.Dq("remote_sid")}catch(c){}else try{g.Bq("remote_sid",a.join(","),-1)}catch(c){}},mya=function(){return g.Us("yt-remote-session-browser-channel")},nya=function(){return g.Us("yt-remote-local-screens")||[]},oya=function(){g.Ts("yt-remote-lounge-token-expiration",!0,86400)},pya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Ic)(nya(),function(d){return d.loungeToken}),c=(0,g.Ic)(a,function(d){return d.loungeToken});
(0,g.vi)(c,function(d){return!g.eb(b,d)})&&oya();
g.Ts("yt-remote-local-screens",a,31536E3)},qya=function(a,b){g.Ts("yt-remote-session-browser-channel",a);
g.Ts("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.eb(c,d)||c.push(d);lya(c);p6()},q6=function(a){a||(g.Vs("yt-remote-session-screen-id"),g.Vs("yt-remote-session-video-id"));
p6();a=m6();g.jb(a,o6());lya(a)},rya=function(){if(!r6){var a=g.no();
a&&(r6=new g.Xn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},sya=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},tya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?uya(a.shift(),function(){s6(a)}):t6()},vya=function(a){return"chrome-extension://"+a+"/cast_sender.js"},uya=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=tya();
a&&a(!1,"No cast extension found")},xya=function(){if(wya){var a=2,b=tya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;uya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},yya=function(){xya();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.z.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Kd=b;this.C=(0,g.x)(this.MF,this);this.o=!1;this.u=0;this.A=this.La=null;this.B=[]},v6=function(a,b,c){g.z.call(this);
this.B=null!=c?a.bind(c):a;this.Kd=b;this.A=null;this.o=!1;this.u=0;this.La=null},w6=function(a){a.La=g.Yf(function(){a.La=null;
a.o&&!a.u&&(a.o=!1,w6(a))},a.Kd);
var b=a.A;a.A=null;a.B.apply(null,b)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Zxa(a)},y6=function(){},z6=function(){},zya=function(){},Bya=function(a){return(a=Aya(a))?new ActiveXObject(a):new XMLHttpRequest},Aya=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.A1(this);this.u=new g.Xf;this.u.setInterval(250)},Dya=function(a,b,c){a.pl=1;
a.xh=$5(b.clone());a.zj=c;a.F=!0;Cya(a,null)},B6=function(a,b,c,d,e){a.pl=1;
a.xh=$5(b.clone());a.zj=null;a.F=c;e&&(a.CC=!1);Cya(a,d)},Cya=function(a,b){a.kl=(0,g.C)();
C6(a);a.ti=a.xh.clone();a6(a.ti,"t",a.G);a.Dn=0;a.Yc=a.o.us(a.o.pn()?b:null);0<a.it&&(a.zq=new v6((0,g.x)(a.FD,a,a.Yc),a.it));a.B.oa(a.Yc,"readystatechange",a.bO);var c=a.bj?g.Rb(a.bj):{};a.zj?(a.er="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Yc.send(a.ti,a.er,a.zj,c)):(a.er="GET",a.CC&&!g.oe&&(c.Connection="close"),a.Yc.send(a.ti,a.er,null,c));a.o.Gf(1)},Gya=function(a,b,c){for(var d=!0;!a.Li&&a.Dn<c.length;){var e=Eya(a,c);
if(e==D6){4==b&&(a.Oh=4,E6(15),d=!1);break}else if(e==Fya){a.Oh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.Oh=1,E6(17),d=!1);a.Nf=a.Nf&&d;d||(G6(a),H6(a))},Eya=function(a,b){var c=a.Dn,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return Fya;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Dn=d+c;return e},Iya=function(a,b){a.kl=(0,g.C)();
C6(a);var c=b?window.location.hostname:"";a.ti=a.xh.clone();Z5(a.ti,"DOMAIN",c);Z5(a.ti,"t",a.G);try{a.Rf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.Oh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in I6)h=I6[l];else if(l in Hya)h=I6[l]=Hya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
I6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.$c(g.bc("b/12014412"),d+"</body></html>");a.Rf.open();a.Rf.write(g.Vc(c));a.Rf.close();a.Rf.parentWindow.m=(0,g.x)(a.rN,a);a.Rf.parentWindow.d=(0,g.x)(a.HB,a,!0);a.Rf.parentWindow.rpcClose=(0,g.x)(a.HB,a,!1);c=a.Rf.createElement("DIV");a.Rf.parentWindow.document.body.appendChild(c);d=g.Cc(a.ti.toString());d=g.hd(g.zc(d));d=g.$c(g.bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ad(c,d);a.o.Gf(1)},C6=function(a){a.dw=(0,g.C)()+a.C;
Jya(a,a.C)},Jya=function(a,b){if(null!=a.wl)throw Error("WatchDog timer not null");
a.wl=J6((0,g.x)(a.zN,a),b)},K6=function(a){a.wl&&(g.v.clearTimeout(a.wl),a.wl=null)},H6=function(a){a.o.Gy()||a.Li||a.o.Po(a)},G6=function(a){K6(a);
g.Le(a.zq);a.zq=null;a.u.stop();g.Ksa(a.B);if(a.Yc){var b=a.Yc;a.Yc=null;b.abort();b.dispose()}a.Rf&&(a.Rf=null)},F6=function(a,b){try{a.o.zB(a,b),a.o.Gf(4)}catch(c){}},Lya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Kya(a,b,function(h){h?c(!0):g.v.setTimeout(function(){Lya(a,b,c,d,f)},f)})}},Kya=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Yxa(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Mya=function(a){this.o=a;
this.u=new y6},Nya=function(a){var b=M6(a.o,a.Ll,"/mail/images/cleardot.gif");
$5(b);Lya(b.toString(),5E3,(0,g.x)(a.ME,a),3,2E3);a.Gf(1)},O6=function(a){var b=a.o.L;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.le=new A6(a,void 0,void 0,void 0),a.le.bj=a.gt,b=a.o,b=M6(b,b.pn()?a.lm:null,a.ht),E6(5),!g.me||g.Rd(10))a6(b,"TYPE","xmlhttp"),B6(a.le,b,!1,a.lm,!1);else{a6(b,"TYPE","html");var c=a.le;a=!!a.lm;c.pl=3;c.xh=$5(b.clone());Iya(c,a)}},P6=function(a){g.mf.call(this);
this.headers=new g.Mm;this.V=a||null;this.A=!1;this.T=this.o=null;this.ga=this.L="";this.F=0;this.B="";this.C=this.ba=this.I=this.Z=!1;this.G=0;this.N=null;this.ea="";this.R=this.aa=!1},Oya=function(a){return g.me&&g.Qd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Pya=function(a){return"content-type"==a.toLowerCase()},Rya=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;Qya(a);Q6(a)},Qya=function(a){a.Z||(a.Z=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Tya=function(a){if(a.A&&"undefined"!=typeof g.F1)if(a.T[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.I&&4==R6(a))g.Yf(a.vB,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.sd(1,String(a.L));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!Sya.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";Qya(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){Uya(a);
var c=a.o,d=a.T[0]?g.Ja:null;a.o=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Uya=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.ga+" "+a.L+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new y6;this.I=a||null;this.L=null!=b?b:null;this.F=c||!1},Vya=function(a,b){this.o=a;
this.map=b;this.context=null},Wya=function(a){g.Ne.call(this,"statevent",a)},Xya=function(a,b){g.Ne.call(this,"timingevent",a);
this.size=b},Yya=function(a){g.Ne.call(this,"serverreachability",a)},aza=function(a){Zya(a);
if(3==a.o){var b=a.Rm++,c=a.Bo.clone();Z5(c,"SID",a.A);Z5(c,"RID",b);Z5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.A,b,void 0);b.pl=2;b.xh=$5(c.clone());Yxa(new Image,b.xh.toString());b.kl=(0,g.C)();C6(b)}$ya(a)},bza=function(a){a.kF(1,0);
a.Bo=M6(a,null,a.ct);W6(a)},Zya=function(a){a.Ah&&(a.Ah.abort(),a.Ah=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Ig&&(g.v.clearTimeout(a.Ig),a.Ig=null);X6(a);a.ce&&(a.ce.cancel(),a.ce=null);a.Gh&&(g.v.clearTimeout(a.Gh),a.Gh=null)},cza=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Vya(a.VJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.ce||a.Gh||(a.Gh=J6((0,g.x)(a.GB,a),0),a.gk=0)},eza=function(a,b){if(1==a.o){if(!b){a.Rm=Math.floor(1E5*Math.random());
var c=a.Rm++,d=new A6(a,"",c,void 0);d.bj=null;var e=Y6(a),f=a.Bo.clone();Z5(f,"RID",c);Z5(f,"CVER","1");V6(a,f);Dya(d,f,e);a.ce=d;a.o=2}}else 3==a.o&&(b?dza(a,b):0==a.u.length||a.ce||dza(a))},dza=function(a,b){if(b)if(6<a.Mi){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Rm-1;var d=Y6(a)}else c=b.I,d=b.zj;else c=a.Rm++,d=Y6(a);var e=a.Bo.clone();Z5(e,"SID",a.A);Z5(e,"RID",c);Z5(e,"AID",a.Ak);V6(a,e);c=new A6(a,a.A,c,a.gk+1);c.bj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ce=c;Dya(c,e,d)},V6=function(a,b){if(a.Hd){var c=a.Hd.dy();
c&&g.Ab(c,function(d,e){Z5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Mi&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.Mi?e:f-d;try{g.Ab(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},fza=function(a){a.Bc||a.Ig||(a.G=1,a.Ig=J6((0,g.x)(a.FB,a),0),a.Sj=0)},Z6=function(a){if(a.Bc||a.Ig||3<=a.Sj)return!1;
a.G++;a.Ig=J6((0,g.x)(a.FB,a),gza(a,a.Sj));a.Sj++;return!0},N6=function(a,b,c){a.ar=c;
a.Yf=b.Yg;a.F||bza(a)},X6=function(a){null!=a.Qi&&(g.v.clearTimeout(a.Qi),a.Qi=null)},gza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Hd&&(c=null);var d=(0,g.x)(a.NO,a);c||(c=new g.Pm("//www.google.com/images/cleardot.gif"),$5(c));Kya(c.toString(),1E4,d)}else E6(2);hza(a,b)},hza=function(a,b){a.o=0;
a.Hd&&a.Hd.rx(b);$ya(a);Zya(a)},$ya=function(a){a.o=0;
a.Yf=-1;if(a.Hd)if(0==a.B.length&&0==a.u.length)a.Hd.Zr();else{g.nb(a.B);var b=g.nb(a.u);a.B.length=0;a.u.length=0;a.Hd.Zr(b)}},M6=function(a,b,c){var d=g.Xm(c);
if(""!=d.o)b&&g.Rm(d,b+"."+d.o),g.Sm(d,d.B);else{var e=window.location;d=bya(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Zl&&g.Ab(a.Zl,function(f,h){Z5(d,h,f)});
Z5(d,"VER",a.Mi);V6(a,d);return d},J6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Wya(a7,a))},iza=function(){},jza=function(){this.o=[];
this.u=[]},kza=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.z.call(this);
this.o=new g.G(this.kN,0,this);g.A(this,this.o);this.Kd=5E3;this.u=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},c7=function(a,b,c){this.N=a;
this.F=b;this.A=new g.Wn;this.u=new b7(this.pO,this);this.o=null;this.Mb=!1;this.C=null;this.L="";this.I=this.B=0;this.G=[];this.R=c||!1},lza=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ar,sessionId:a.o.A,arrayId:a.o.Ak}},mza=function(a,b){a.I=b||0;
a.u.stop();a.o&&(3==a.o.o&&eza(a.o),aza(a.o));a.I=0},d7=function(a){return!!a.o&&3==a.o.o},nza=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.sd(4,a))||"";b&&(this.port=":"+b);this.domain=g.td(a)||"";a=g.Oc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.vc(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Dd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.B,d,!0),onError:g.Ra(a.A,e),Fe:g.Ra(a.C,e)};c&&(a.Db=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uq(b,a)},rza=function(){var a=oza;
pza();h7.push(a);qza(h7)},i7=function(a,b){pza();
var c=h7,d=sza(a,String(b));g.fb(c)?tza(d):(qza(c),(0,g.y)(c,function(e){e(d)}))},pza=function(){h7||(h7=g.Ia("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",h7,void 0))},tza=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},qza=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},sza=function(a,b){var c=((0,g.C)()-uza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.N.call(this);
this.F=a;this.screens=[]},vza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},wza=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.ze)(a.screens,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=vza(a,b[d])||c;return c},xza=function(a,b){var c=a.screens.length;
a.screens=(0,g.ze)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},n7=function(a,b,c,d){g.N.call(this);
this.F=a;this.B=b;this.C=c;this.A=d;this.u=0;this.o=null;this.La=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;o7(this);this.info("Initializing with "+i6(this.screens))},yza=function(a){if(a.screens.length){var b=(0,g.Ic)(a.screens,function(d){return d.id}),c=f7(a.u,"/pairing/get_lounge_token_batch");
g7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.WF,a),(0,g.x)(a.VF,a))}},o7=function(a){var b=hya(nya());
b=(0,g.ze)(b,function(c){return!c.uuid});
return wza(a,b)},q7=function(a,b){pya((0,g.Ic)(a.screens,fya));
b&&oya()},s7=function(a,b){g.N.call(this);
this.F=b;var c=g.Us("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.eb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;r7("Initialized with "+g.Lk(this.o))},zza=function(a,b,c){var d=f7(a.C,"/pairing/get_screen_availability");
g7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(b6(b)!=b6(a.o))var c=!1;
else{c=g.Hb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Lk(a.o)),a.o=b,a.S("screenChange"));Aza(a)},u7=function(a){isNaN(a.A)||g.Mo(a.A);
a.A=g.Ko((0,g.x)(a.dv,a),0<a.B&&a.B<(0,g.C)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Bza=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.lc("Requesting availability of screen w/o lounge token.")});
return b},Aza=function(a){a=g.Hb(g.Bb(a.o,function(b){return b}));
g.vb(a);a.length?g.Ts("yt-remote-online-screen-ids",a.join(","),60):g.Vs("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};Cza(this)},Eza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.xe();if(h=(c?l6(h,c):null)||l6(h,b)){h.uuid=b;var l=w7(a,h);zza(a.o,l,function(m){e(m?l:null)})}else c?Dza(a,c,(0,g.x)(function(m){var n=w7(this,new f6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));zza(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},Fza=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},Dza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Db:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.uq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Gza=function(a){a.screens=a.u.xe();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.screens))},Cza=function(a){x7(a);
a.u=new p7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.eG,a));Gza(a);a.A=hya(g.Us("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+i6(a.A));a.o=new s7(a.C,(0,g.x)(a.xe,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ts("yt-remote-automatic-screen-cache",(0,g.Ic)(a.A,fya)));x7(a);a.B[b.uuid]=b.id;g.Ts("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Us("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.N.call(this);
this.T=c;this.L=a;this.u=b;this.I=null},z7=function(a,b){i7(a.T,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.sP,this);this.B=(0,g.x)(this.HN,this);this.A=g.Ko((0,g.x)(function(){Hza(this,null)},this),12E4)},Iza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Lk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Lk(b))},Hza=function(a,b){g.Mo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.mq,a),d=(0,g.x)(a.Ee,a);a.yy(b,c,d,5)}}else a.Ee(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.V=c;this.B=null;this.F=g.Ja;this.C=NaN;this.R=(0,g.x)(this.vP,this);this.o=g.Ja},Jza=function(a){a.o=a.L.LD(a.N,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.mq(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.Ee(b)},a))},Kza=function(a){var b={};
b.pairingCode=a.N;b.theme=a.V;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}rya()&&(b.env_useStageMdx=1);return g.Bd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Ko((0,g.x)(this.Bk,this,null),150)},D7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.yM,this)},Lza=function(a,b){return b?g.bb(a.A,function(c){return g6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},oza=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.C||!!a.A.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.Le(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.EB,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.Bk(null)):a.S("yt-remote-cast2-session-change",null))},Mza=function(a){var b=a.u.KD(),c=a.o&&a.o.u;
a=(0,g.Ic)(b,function(d){c&&g6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Lza(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Sza=function(a,b,c,d,e,f,h){Nza()?Oza(b,e,f,h)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Pza(a,c):(window.__onGCastApiAvailable=function(l,m){l?Pza(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),g.Vs("yt-remote-cast-available"),g.Vs("yt-remote-cast-receiver"),Qza(),c(!1))},d?g.Wo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?yya():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(xya(),s6(Rza.map(vya))))):H7("Cannot initialize because not running Chrome")},Qza=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Tza(!1);g.So(M7);M7.length=0},N7=function(){return!!g.Us("yt-remote-cast-installed")},Uza=function(){var a=g.Us("yt-remote-cast-receiver");
return a?a.friendlyName:null},Vza=function(){H7("clearCurrentReceiver");
g.Vs("yt-remote-cast-receiver")},Wza=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Ro("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Nza=function(){var a=0<=g.Oc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Mw||a},Xza=function(a,b){L7().init(a,b)},Oza=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ts("yt-remote-cast-available",f);d6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Ts("yt-remote-cast-receiver",f);d6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Ts("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+h6(f));
f||g.Vs("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.Ia("yt.mdx.remote.cloudview.instance_")},Pza=function(a,b){K7(!0);
I7(!1);Xza(a,function(c){c?(Tza(!0),g.To("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),g.Vs("yt-remote-cast-available"),g.Vs("yt-remote-cast-receiver"),Qza());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Ts("yt-remote-cast-installed",a)},O7=function(){return!!g.Ia("yt.mdx.remote.cloudview.apiReady_")},Tza=function(a){H7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Zf=!1;this.L=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Zf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.C)();a.C=0;a.u=0;a.I=0;a.L=0;a.B=NaN;a.A=!1},T7=function(a){return a.ob()?((0,g.C)()-a.F)/1E3:0},U7=function(a,b){a.G=b;
a.F=(0,g.C)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Sb(a.o);b.hasPrevious=a.Zf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.L;b.liveIngestionTime=a.B;return b},Z7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new jza;this.A=this.u=null;this.L=(0,g.x)(this.CK,this);this.G=(0,g.x)(this.Sm,this);this.I=(0,g.x)(this.BK,this);this.N=(0,g.x)(this.MK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.hw,this),Yza(this))):c=3;0!=c&&(b?this.hw(c):g.Ko((0,g.x)(function(){this.hw(c)},this),0));
var d=Wza();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},$7=function(a){return new R7(a.B.getPlayerContextData())},Yza=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ra(this.vM,b),this))},a)},Zza=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},a8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.B.sendMessage(b,c)},b8=function(a,b){Zza(a);
a.B.setPlayerContextData(X7(b));Yza(a)},Y7=function(a,b){a.A&&(a.A.removeUpdateListener(a.L),a.A.removeMediaListener(a.G),a.Sm(null));
a.A=b;a.A&&(i7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.L),a.A.addMediaListener(a.G),a.A.media.length&&a.Sm(a.A.media[0]))},$za=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.lc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.lc("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.L=this.N=NaN;this.T=[];this.B=this.F=this.A=this.gb=this.o=null;this.Z=a;this.T.push(g.gp(window,"beforeunload",(0,g.x)(this.OF,this)));this.u=[];this.gb=new R7;this.V=b.id;this.o=aAa(this,c);this.o.subscribe("handlerOpened",this.GK,this);this.o.subscribe("handlerClosed",this.DK,this);this.o.subscribe("handlerError",this.EK,this);this.o.subscribe("handlerMessage",this.FK,this);nza(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.gb.videoId;
g.Ws()&&g.Ts("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},aAa=function(a,b){return new c7(f7(a.Z,"/bc"),b)},h8=function(a,b){a.S("proxyStateChange",b)},bAa=function(a){a.C=g.Ko((0,g.x)(function(){g8("Connecting timeout");
this.bk(1)},a),2E4)},i8=function(a){g.Mo(a.C);
a.C=NaN},j8=function(a){g.Mo(a.N);
a.N=NaN},cAa=function(a){k8(a);
a.L=g.Ko((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Mo(a.L);
a.L=NaN},eAa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.C))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.vy()&&a.gb.reset(),h8(a,1),l8(a,"getNowPlaying"),dAa(a)):a.bk(1)},fAa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.gb.videoId&&(g.Nb(b.params)?a.gb.o=null:a.gb.o=b.params,a.S("remotePlayerChange"))},gAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.gb.listId=b.params.listId||a.gb.listId;W7(a.gb,c,d);a.S("remoteQueueChange")},iAa=function(a,b){b.params=b.params||{};
gAa(a,b);hAa(a,b);a.S("autoplayDismissed")},hAa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.gb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.gb.playerState&&(c=-1E3);a.gb.playerState=c;c=Number(b.params.loadedTime);a.gb.L=isNaN(c)?0:c;c=Number(b.params.duration);a.gb.I=isNaN(c)?0:c;c=a.gb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.gb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.gb.playerState?cAa(a):k8(a);a.S("remotePlayerChange")},jAa=function(a,b){if(-1E3!=
a.gb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.gb.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.gb,isNaN(c)?0:c);a.S("remotePlayerChange")}},kAa=function(a,b){var c="true"==b.params.muted;
a.gb.volume=parseInt(b.params.volume,10);a.gb.muted=c;a.S("remotePlayerChange")},lAa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},mAa=function(a,b){var c="true"==b.params.hasNext;
a.gb.Zf="true"==b.params.hasPrevious;a.gb.hasNext=c;a.S("previousNextChange")},dAa=function(a){g.Mo(a.I);
a.I=g.Ko((0,g.x)(a.bk,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Lk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Jd=a;this.o=[];this.o.push(this.Jd.$_s("screenChange",(0,g.x)(this.qP,this)));this.o.push(this.Jd.$_s("onlineScreenChange",(0,g.x)(this.YL,this)))},rAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.J("MDX_CONFIG")||b;jya();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),rya()&&(n8.o="/api/loungedev"));o8||(o8=g.Ia("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",o8,void 0));nAa();var c=p8();if(!c){var d=new v7(n8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);Sza(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){d6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ia("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Lk(b)),s8.push(g.Ro("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")})),s8.push(g.Ro("yt-remote-cast2-receiver-selected",function(){t8(null);
d6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Ro("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Ro("yt-remote-cast2-session-change",oAa)),s8.push(g.Ro("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Vza())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.Ao("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),r8(" -- with channel params: "+
g.Lk(a)),pAa(a),c.start(),q8()||qAa())},tAa=function(){var a=sAa();
N7()&&g.Us("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},sAa=function(){var a=p8().Jd.$_gos();
var b=w8();b&&x8()&&(k6(a,b)||a.push(b));return iya(a)},y8=function(){var a=uAa();
!a&&N7()&&Uza()&&(a={key:"cast-selector-receiver",name:Uza()});return a},uAa=function(){var a=sAa(),b=w8();
b||(b=u8());return g.bb(a,function(c){return b&&g6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().xe();return l6(b,a)},oAa=function(a){r8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.Ia("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.Ia("yt.mdx.remote.currentScreenId_")},vAa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},wAa=function(){return g.Ia("yt.mdx.remote.connectData_")},t8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.Ia("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||vAa("");g.Ga("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},u8=function(){var a=g.Ws();
if(!a)return null;var b=p8();if(!b)return null;b=b.xe();return l6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{vAa(a.id);var c=new f8(n8,a,v8());c.connect(b,wAa());c.subscribe("beforeDisconnect",function(d){d6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},qAa=function(){var a=u8();
a?(r8("Resume connection to: "+h6(a)),A8(a,0)):(q6(),Vza(),r8("Skipping connecting because no session screen found."))},nAa=function(){var a=v8();
if(g.Nb(a)){a=o6();var b=g.Us("yt-remote-session-name")||"",c=g.Us("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.Ia("yt.mdx.remote.channelParams_")||{}},pAa=function(a){a?(g.Ts("yt-remote-session-app",a.app),g.Ts("yt-remote-session-name",a.name)):(g.Vs("yt-remote-session-app"),g.Vs("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.z.call(this);
var d=this;this.module=a;this.H=b;this.Ya=c;this.events=new g.Yr(this);this.L=this.events.M(this.H,"onVolumeChange",this.eB);this.B=!1;this.suggestion=null;this.C=new g.wC(64);this.o=new g.G(this.OC,500,this);this.u=new g.G(this.PC,1E3,this);this.G=new u6(this.VO,0,this);this.A={};this.I=new g.G(this.vD,1E3,this);this.F=new v6(this.seekTo,1E3,this);this.N=g.Ja;g.A(this,this.events);this.events.M(b,"onCaptionsTrackListChanged",this.vL);this.events.M(b,"captionschanged",this.AK);this.events.M(b,"captionssettingschanged",
this.RC);this.events.M(b,"videoplayerreset",this.nq);this.events.M(b,"mdxautoplaycancel",function(){d.Ya.Mx()});
a=this.Ya;a.ha();a.subscribe("proxyStateChange",this.yB,this);a.subscribe("remotePlayerChange",this.Ym,this);a.subscribe("remoteQueueChange",this.nq,this);a.subscribe("previousNextChange",this.uB,this);a.subscribe("nowAutoplaying",this.qB,this);a.subscribe("autoplayDismissed",this.PA,this);g.A(this,this.o);g.A(this,this.u);g.A(this,this.G);g.A(this,this.I);g.A(this,this.F);this.RC();this.nq();this.Ym()},xAa=function(a){a.Zb(0);
a.o.stop();H8(a,new g.wC(64))},J8=function(a,b){if(I8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Ub(c,b));a.Ya.ID(a.H.getVideoData(1).videoId,c);a.A=$7(a.Ya).o}},K8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.Ya.playVideo(c.videoId,b,d,e,c.playerParams,c.wf,Wxa(c));H8(a,new g.wC(1))},yAa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Xy:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},I8=function(a){return $7(a.Ya).videoId===a.H.getVideoData(1).videoId},H8=function(a,b){a.u.stop();
var c=a.C;if(!g.CC(c,b)){var d=g.S(b,2);d!==g.S(a.C,2)&&g.tT(a.H.app,d);a.C=b;zAa(a.module,c,b)}},L8=function(){g.T.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",W:"\u4f7f\u7528\u914d\u5bf9\u7801\u5728\u7f51\u9875\u4e0a\u5173\u8054\u60a8\u7684\u7535\u89c6\u7684\u529f\u80fd\u5373\u5c06\u505c\u7528"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],W:"\u4e86\u89e3\u8be6\u60c5"},{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],
W:"\u786e\u5b9a"}]}]}]});this.o=new g.LN(this,250);this.learnMoreButton=this.da("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.da("ytp-mdx-manual-pairing-popup-ok");g.A(this,this.o);this.M(this.learnMoreButton,"click",this.u);this.M(this.okButton,"click",this.A)},M8=function(){g.T.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",W:"\u60a8\u5df2\u9000\u51fa\u5e10\u53f7"},{D:"div",J:"ytp-mdx-popup-description",W:"\u60a8\u89c2\u770b\u7684\u89c6\u9891\u53ef\u80fd\u4f1a\u6dfb\u52a0\u5230\u7535\u89c6\u7684\u89c2\u770b\u8bb0\u5f55\u4e2d\uff0c\u5e76\u5f71\u54cd\u7535\u89c6\u4e0a\u7684\u63a8\u8350\u5185\u5bb9\u3002\u4e3a\u907f\u514d\u53d1\u751f\u8fd9\u79cd\u60c5\u51b5\uff0c\u8bf7\u53d6\u6d88\u5e76\u5728\u8ba1\u7b97\u673a\u4e0a\u767b\u5f55 YouTube\u3002"},
{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"\u53d6\u6d88"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"\u786e\u8ba4"}]}]}]});this.o=new g.LN(this,250);this.cancelButton=this.da("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.da("ytp-mdx-privacy-popup-confirm");g.A(this,this.o);this.M(this.cancelButton,"click",this.u);this.M(this.confirmButton,"click",this.A)},N8=function(a){g.T.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.UL()]},{D:"div",J:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.api=a;this.o=new g.LN(this,250);g.A(this,this.o);this.M(a,"presentingplayerstatechange",this.u);AAa(this,g.NL(a))},AAa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.S(b,128)?g.rL("\u5728$RECEIVER_NAME\u4e0a\u51fa\u73b0\u9519\u8bef",c):b.ob()||g.S(b,4)?g.rL("\u6b63\u5728$RECEIVER_NAME\u4e0a\u64ad\u653e",c):g.rL("\u5df2\u8fde\u63a5\u5230$RECEIVER_NAME",c);a.na("statustext",c);a.o.show()}else a.o.hide()},O8=function(a,b){g.gR.call(this,"\u64ad\u653e\u8bbe\u5907",0,a,b);
this.H=a;this.si={};this.M(a,"onMdxReceiversChange",this.B);this.M(a,"presentingplayerstatechange",this.B);this.B()},P8=function(a){g.rN.call(this,a);
this.Bf={key:j6(),name:"\u6b64\u8ba1\u7b97\u673a"};this.re=null;this.subscriptions=[];this.Pu=this.Ya=null;this.si=[this.Bf];this.Ch=this.Bf;this.Rb=new g.wC(64);this.oz=0;this.hd=-1;this.Dk=null;this.Zm=this.tp=!1;this.yj=this.dl=null;if(!g.Ey(this.player.O())){a=this.player;var b=g.FM(a);b&&(b=b.Im())&&(b=new O8(a,b),g.A(this,b));b=new N8(a);g.A(this,b);g.fN(a,b.element,4);this.dl=new M8;g.A(this,this.dl);g.fN(a,this.dl.element,4);g.P(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.Dk=new L8,g.A(this,this.Dk),g.fN(a,this.Dk.element,4));this.Zm=!!u8();this.tp=!!g.Us("yt-remote-manual-pairing-warning-shown")}},Q8=function(a){a.yj&&(a.player.removeEventListener("presentingplayerstatechange",a.yj),a.yj=null)},zAa=function(a,b,c){a.Rb=c;
a.player.S("presentingplayerstatechange",new g.HC(c,b))},BAa=function(a,b,c){var d=!1;
1===b?d=!a.Zm:2===b&&(d=!a.tp);d&&g.JC(c,8)&&(a.player.pauseVideo(),Q8(a))},R8=function(a,b){if(b.key!==a.Ch.key)if(b.key===a.Bf.key)z8();
else{if(a.Dk&&!a.tp&&b!==a.Bf&&"cast-selector-receiver"!==b.key&&g.Ny(a.player.O()))CAa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.J("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.J("SESSION_INDEX")&&!g.J("LOGGED_IN")))||a.Zm||!a.dl);(c?0:g.Ny(a.player.O())||g.Ry(a.player.O()))&&DAa(a)}a.Ch=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Da(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.wf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Wxa(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+g.Lk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=
c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?d6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().xe(),(c=l6(c,b.key))&&A8(c,1))}},DAa=function(a){g.NL(a.player).ob()?a.player.pauseVideo():(a.yj=function(b){BAa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.yj));
a.dl&&a.dl.fc();x8()||(E8=!0)},CAa=function(a){g.NL(a.player).ob()?a.player.pauseVideo():(a.yj=function(b){BAa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.yj));
a.Dk&&a.Dk.fc();x8()||(E8=!0)},Hya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},EAa={},eya={XP:"atp",OS:"ska",zS:"que",PR:"mus",NS:"sus",VQ:"dsp",GS:"seq"},r6,n6="",wya=sya("loadCastFramework")||sya("loadCastApplicationFramework"),Rza=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(u6,g.z);g.k=u6.prototype;g.k.LF=function(a){this.B=arguments;this.o=!1;this.La?this.A=(0,g.C)()+this.Kd:this.La=g.Yf(this.C,this.Kd)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();u6.sc.X.call(this)};
g.k.MF=function(){this.A?(this.La=g.Yf(this.C,this.A-(0,g.C)()),this.A=null):(this.La=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(v6,g.z);g.k=v6.prototype;g.k.Cz=function(a){this.A=arguments;this.La||this.u?this.o=!0:w6(this)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.La||(this.o=!1,w6(this))};
g.k.X=function(){g.z.prototype.X.call(this);this.stop()};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Aya(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ta(zya,z6);S8=new zya;g.k=A6.prototype;g.k.bj=null;g.k.Nf=!1;g.k.wl=null;g.k.dw=null;g.k.kl=null;g.k.pl=null;g.k.xh=null;g.k.ti=null;g.k.zj=null;g.k.Yc=null;g.k.Dn=0;g.k.Rf=null;g.k.er=null;g.k.Oh=null;g.k.mm=-1;g.k.CC=!0;g.k.Li=!1;g.k.it=0;g.k.zq=null;var Fya={},D6={};g.k=A6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.bO=function(a){a=a.target;var b=this.zq;b&&3==R6(a)?b.Cz():this.FD(a)};
g.k.FD=function(a){try{if(a==this.Yc)a:{var b=R6(this.Yc),c=this.Yc.F,d=this.Yc.getStatus();if(g.me&&!g.Rd(10)||g.oe&&!g.Qd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.zh&&!T6(this.Yc))break a;this.Li||4!=b||7==c||(8==c||0>=d?this.o.Gf(3):this.o.Gf(2));K6(this);var e=this.Yc.getStatus();this.mm=e;var f=T6(this.Yc);(this.Nf=200==e)?(4==b&&G6(this),this.F?(Gya(this,b,f),g.zh&&this.Nf&&3==b&&(this.B.oa(this.u,"tick",this.UN),this.u.start())):F6(this,f),this.Nf&&!this.Li&&(4==b?this.o.Po(this):(this.Nf=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Oh=3,E6(13)):(this.Oh=0,E6(14)),G6(this),H6(this))}}catch(h){this.Yc&&T6(this.Yc)}finally{}};
g.k.UN=function(){var a=R6(this.Yc),b=T6(this.Yc);this.Dn<b.length&&(K6(this),Gya(this,a,b),this.Nf&&4!=a&&C6(this))};
g.k.rN=function(a){J6((0,g.x)(this.qN,this,a),0)};
g.k.qN=function(a){this.Li||(K6(this),F6(this,a),C6(this))};
g.k.HB=function(a){J6((0,g.x)(this.pN,this,a),0)};
g.k.pN=function(a){this.Li||(G6(this),this.Nf=a,this.o.Po(this),this.o.Gf(4))};
g.k.cancel=function(){this.Li=!0;G6(this)};
g.k.zN=function(){this.wl=null;var a=(0,g.C)();0<=a-this.dw?(2!=this.pl&&this.o.Gf(3),G6(this),this.Oh=2,E6(18),H6(this)):Jya(this,this.dw-a)};
g.k.getLastError=function(){return this.Oh};g.k=Mya.prototype;g.k.gt=null;g.k.le=null;g.k.Aq=!1;g.k.Hy=null;g.k.yo=null;g.k.Nt=null;g.k.ht=null;g.k.Re=null;g.k.Yg=-1;g.k.lm=null;g.k.Ll=null;g.k.connect=function(a){this.ht=a;a=M6(this.o,null,this.ht);E6(3);this.Hy=(0,g.C)();var b=this.o.I;null!=b?(this.lm=b[0],(this.Ll=b[1])?(this.Re=1,Nya(this)):(this.Re=2,O6(this))):(a6(a,"MODE","init"),this.le=new A6(this,void 0,void 0,void 0),this.le.bj=this.gt,B6(this.le,a,!1,null,!0),this.Re=0)};
g.k.ME=function(a){if(a)this.Re=2,O6(this);else{E6(4);var b=this.o;b.Yf=b.Ah.Yg;$6(b,9)}a&&this.Gf(2)};
g.k.us=function(a){return this.o.us(a)};
g.k.abort=function(){this.le&&(this.le.cancel(),this.le=null);this.Yg=-1};
g.k.Gy=function(){return!1};
g.k.zB=function(a,b){this.Yg=a.mm;if(0==this.Re)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.Yf=this.Yg;$6(c,2);return}this.lm=c[0];this.Ll=c[1]}else c=this.o,c.Yf=this.Yg,$6(c,2);else if(2==this.Re)if(this.Aq)E6(7),this.Nt=(0,g.C)();else if("11111"==b){if(E6(6),this.Aq=!0,this.yo=(0,g.C)(),c=this.yo-this.Hy,!g.me||g.Rd(10)||500>c)this.Yg=200,this.le.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.yo=this.Nt=(0,g.C)(),this.Aq=!1};
g.k.Po=function(){this.Yg=this.le.mm;if(this.le.Nf)0==this.Re?this.Ll?(this.Re=1,Nya(this)):(this.Re=2,O6(this)):2==this.Re&&((!g.me||g.Rd(10)?!this.Aq:200>this.Nt-this.yo)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.Re?E6(9):2==this.Re&&E6(10);var a=this.o;this.le.getLastError();a.Yf=this.Yg;$6(a,2)}};
g.k.pn=function(){return this.o.pn()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Gf=function(a){this.o.Gf(a)};g.Ta(P6,g.mf);var Sya=/^https?$/i,FAa=["POST","PUT"];g.k=P6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.L+"; newUri="+a);b=b?b.toUpperCase():"GET";this.L=a;this.B="";this.F=0;this.ga=b;this.Z=!1;this.A=!0;this.o=this.V?Bya(this.V):Bya(S8);this.T=this.V?this.V.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.vB,this);try{c6(S6(this,"Opening Xhr")),this.ba=!0,this.o.open(b,String(a),!0),this.ba=!1}catch(f){c6(S6(this,"Error opening Xhr: "+f.message));Rya(this,f);return}a=
c||"";var e=this.headers.clone();d&&aya(d,function(f,h){e.set(h,f)});
d=g.bb(e.Pe(),Pya);c=g.v.FormData&&a instanceof g.v.FormData;!g.eb(FAa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{Uya(this),0<this.G&&(this.R=Oya(this.o),c6(S6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Iy,this)):this.N=g.Yf(this.Iy,this.G,this)),c6(S6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){c6(S6(this,"Send error: "+f.message)),Rya(this,f)}};
g.k.Iy=function(){"undefined"!=typeof g.F1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,S6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(S6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),Q6(this,!0));P6.sc.X.call(this)};
g.k.vB=function(){this.ha()||(this.ba||this.I||this.C?Tya(this):this.xM())};
g.k.xM=function(){Tya(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=U6.prototype;g.k.Zl=null;g.k.ce=null;g.k.Bc=null;g.k.ct=null;g.k.Bo=null;g.k.fx=null;g.k.Oo=null;g.k.Rm=0;g.k.VJ=0;g.k.Hd=null;g.k.Gh=null;g.k.Ig=null;g.k.Qi=null;g.k.Ah=null;g.k.ar=null;g.k.Ak=-1;g.k.nz=-1;g.k.Yf=-1;g.k.gk=0;g.k.Sj=0;g.k.Mi=8;var a7=new g.mf;g.Ta(Wya,g.Ne);g.Ta(Xya,g.Ne);g.Ta(Yya,g.Ne);g.k=U6.prototype;g.k.connect=function(a,b,c,d,e){E6(0);this.ct=b;this.Zl=c||{};d&&void 0!==e&&(this.Zl.OSID=d,this.Zl.OAID=e);this.F?(J6((0,g.x)(this.zx,this,a),100),bza(this)):this.zx(a)};
g.k.zx=function(a){this.Ah=new Mya(this);this.Ah.gt=null;this.Ah.u=this.C;this.Ah.connect(a)};
g.k.Gy=function(){return 0==this.o};
g.k.GB=function(a){this.Gh=null;eza(this,a)};
g.k.FB=function(){this.Ig=null;this.Bc=new A6(this,this.A,"rpc",this.G);this.Bc.bj=null;this.Bc.it=0;var a=this.fx.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.A);Z5(a,"CI",this.ar?"0":"1");Z5(a,"AID",this.Ak);V6(this,a);if(!g.me||g.Rd(10))Z5(a,"TYPE","xmlhttp"),B6(this.Bc,a,!0,this.Oo,!1);else{Z5(a,"TYPE","html");var b=this.Bc,c=!!this.Oo;b.pl=3;b.xh=$5(a.clone());Iya(b,c)}};
g.k.zB=function(a,b){if(0!=this.o&&(this.Bc==a||this.ce==a))if(this.Yf=a.mm,this.ce==a&&3==this.o)if(7<this.Mi){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Ig){if(this.Bc)if(this.Bc.kl+3E3<this.ce.kl)X6(this),this.Bc.cancel(),this.Bc=null;else break a;Z6(this);E6(19)}}else this.nz=c[1],0<this.nz-this.Ak&&37500>c[2]&&this.ar&&0==this.Sj&&!this.Qi&&(this.Qi=J6((0,g.x)(this.wK,this),6E3));else $6(this,11)}else b!=EAa.uQ.o&&$6(this,11);else if(this.Bc==
a&&X6(this),!g.jc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Ak=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Oo=e[2],e=e[3],null!=e?this.Mi=e:this.Mi=6,this.o=3,this.Hd&&this.Hd.tx(),this.fx=M6(this,this.pn()?this.Oo:null,this.ct),fza(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Hd&&this.Hd.sx(e),this.Sj=0)}}};
g.k.wK=function(){null!=this.Qi&&(this.Qi=null,this.Bc.cancel(),this.Bc=null,Z6(this),E6(20))};
g.k.Po=function(a){if(this.Bc==a){X6(this);this.Bc=null;var b=2}else if(this.ce==a)this.ce=null,b=1;else return;this.Yf=a.mm;if(0!=this.o)if(a.Nf)1==b?(b=(0,g.C)()-a.kl,a7.dispatchEvent(new Xya(a7,a.zj?a.zj.length:0,b,this.gk)),W6(this),this.B.length=0):fza(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Yf)){if(d=1==b)this.ce||this.Gh||1==this.o||2<=this.gk?d=!1:(this.Gh=J6((0,g.x)(this.GB,this,a),gza(this,this.gk)),this.gk++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.k.kF=function(a){if(!g.eb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.NO=function(a){a?E6(2):(E6(1),hza(this,8))};
g.k.us=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.aa=!1;return a};
g.k.isActive=function(){return!!this.Hd&&this.Hd.isActive(this)};
g.k.Gf=function(a){a7.dispatchEvent(new Yya(a7,a))};
g.k.pn=function(){return!(!g.me||g.Rd(10))};
g.k=iza.prototype;g.k.tx=function(){};
g.k.sx=function(){};
g.k.rx=function(){};
g.k.Zr=function(){};
g.k.dy=function(){return{}};
g.k.isActive=function(){return!0};g.k=jza.prototype;g.k.isEmpty=function(){return g.fb(this.o)&&g.fb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.eb(this.o,a)||g.eb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Psa)(b,a);0<=c?(g.ib(b,c),b=!0):b=!1;return b||g.jb(this.u,a)};
g.k.Sd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(b7,g.z);g.k=b7.prototype;g.k.kN=function(){this.Kd=Math.min(3E5,2*this.Kd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Kd+15E3*Math.random();this.o.fb(a);this.u=(0,g.C)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Kd=5E3};g.Ta(c7,iza);g.k=c7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.ki=function(a){return this.A.cj(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Mb||(this.Mb=!0,g.Le(this.A),mza(this),g.Le(this.u),this.u=null)};
g.k.ha=function(){return this.Mb};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.L="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Hd=null);d.Hd=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.Ak):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Ub(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):d7(this)&&cza(this.o,c)};
g.k.tx=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)cza(this.o,a[b])}this.S("handlerOpened")};
g.k.rx=function(a){var b=2==a&&401==this.o.Yf;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.Zr=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.dy=function(){var a={v:2};this.L&&(a.gsessionid=this.L);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Ub(a,this.C);return a};
g.k.sx=function(a){"S"==a[0]?this.L=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),aza(this.o)):this.S("handlerMessage",new kza(a[0],a[1]))};
g.k.pO=function(){this.u.isActive();var a=this.o,b=0;a.Bc&&b++;a.ce&&b++;0==b&&this.connect(this.C,this.B)};e7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.C=function(a){a(Error("request timed out"))};var uza=(0,g.C)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ta(m7,g.N);m7.prototype.xe=function(){return this.screens};
m7.prototype.contains=function(a){return!!k6(this.screens,a)};
m7.prototype.get=function(a){return a?l6(this.screens,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.t(n7,g.N);g.k=n7.prototype;g.k.start=function(){!this.o&&isNaN(this.La)&&this.JD()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.La)||(g.Mo(this.La),this.La=NaN)};
g.k.X=function(){this.stop();g.N.prototype.X.call(this)};
g.k.JD=function(){this.La=NaN;this.o=g.uq(f7(this.F,"/pairing/get_screen"),{method:"POST",Db:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.oP,this),onError:(0,g.x)(this.nP,this),Fe:(0,g.x)(this.pP,this)})};
g.k.oP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.A;this.S("pairingComplete",new f6(c))};
g.k.nP=function(a){this.o=null;a.status&&404==a.status?this.u>=GAa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=GAa[this.u],this.La=g.Ko((0,g.x)(this.JD,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.pP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var GAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(p7,m7);g.k=p7.prototype;g.k.start=function(){o7(this)&&this.S("screenChange");!g.Us("yt-remote-lounge-token-expiration")&&yza(this);g.Mo(this.o);this.o=g.Ko((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){o7(this);vza(this,a);q7(this,!1);this.S("screenChange");b(a);a.token||yza(this)};
g.k.remove=function(a,b){var c=o7(this);xza(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.Yq=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.Mo(this.o);p7.sc.X.call(this)};
g.k.WF=function(a){o7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.k.VF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.t(s7,g.N);g.k=s7.prototype;g.k.start=function(){var a=parseInt(g.Us("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.C)()-144E5<a?0:a)?u7(this):(this.B=(0,g.C)()+3E5,g.Ts("yt-remote-fast-check-period",this.B),this.dv())};
g.k.isEmpty=function(){return g.Nb(this.o)};
g.k.update=function(){r7("Updating availability on schedule.");var a=this.F(),b=g.Bb(this.o,function(c,d){return c&&!!l6(a,d)},this);
t7(this,b)};
g.k.X=function(){g.Mo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.k.dv=function(){g.Mo(this.A);this.A=NaN;this.u&&this.u.abort();var a=Bza(this);if(b6(a)){var b=f7(this.C,"/pairing/get_screen_availability");this.u=g7(this.C,b,{lounge_token:g.Hb(a).join(",")},(0,g.x)(this.UM,this,a),(0,g.x)(this.TM,this))}else t7(this,{}),u7(this)};
g.k.UM=function(a,b){this.u=null;var c=g.Hb(Bza(this));if(g.xb(c,g.Hb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.lc("Changing Screen set during request."),this.dv()};
g.k.TM=function(a){this.lc("Screen availability failed: "+a);this.u=null;u7(this)};
g.k.lc=function(a){i7("OnlineScreenService",a)};g.Ta(v7,m7);g.k=v7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.Yq=function(a,b,c,d){this.u.contains(a)?this.u.Yq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.k.xe=function(a){return a?this.screens:g.lb(this.screens,(0,g.ze)(this.A,function(b){return!this.contains(b)},this))};
g.k.KD=function(){return(0,g.ze)(this.xe(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.LD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Le(f);d(w7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Le(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.rP=function(a,b,c,d){g.uq(f7(this.C,"/pairing/get_screen"),{method:"POST",Db:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new f6(f.screen||{});if(!h.name||Fza(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);Fza(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(w7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Fe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Le(this.u);g.Le(this.o);v7.sc.X.call(this)};
g.k.eG=function(){Gza(this);this.S("screenChange");this.o.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ta(y7,g.N);g.k=y7.prototype;g.k.getScreen=function(){return this.I};
g.k.mq=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Ee=function(a){this.ha()||(a&&z7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){i7(this.T,a)};
g.k.ND=function(){return null};
g.k.vv=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.vv("");y7.sc.X.call(this)};g.t(A7,y7);g.k=A7.prototype;g.k.tv=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Iza(this)};
g.k.Bk=function(a){this.info("launchWithParams no-op for Cast: "+g.Lk(a))};
g.k.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Ee()},this),(0,g.x)(function(){this.Ee(Error("Failed to stop receiver app."))},this)):this.Ee(Error("Stopping cast device witout session."))};
g.k.vv=function(){};
g.k.X=function(){this.info("disposeInternal");g.Mo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;y7.prototype.X.call(this)};
g.k.HN=function(a,b){if(!this.ha())if(b){var c=x6(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Lk(c));switch(d){case "mdxSessionStatus":Hza(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.k.yy=function(a,b,c,d){Eza(this.L,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ko((0,g.x)(this.yy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.ND=function(){return this.o};
g.k.sP=function(a){this.ha()||a||(z7(this,"Cast session died."),this.Ee())};g.t(B7,y7);g.k=B7.prototype;g.k.tv=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.Bk=function(a){this.B=a;this.F()};
g.k.stop=function(){this.o();this.o=g.Ja;g.Mo(this.C);this.A?this.A.stop((0,g.x)(this.Ee,this,null),(0,g.x)(this.Ee,this,"Failed to stop DIAL device.")):this.Ee()};
g.k.X=function(){this.o();this.o=g.Ja;g.Mo(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;y7.prototype.X.call(this)};
g.k.vP=function(a){this.ha()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.Ee())};
g.k.xt=function(a){this.N=j6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Kza(this));a(b);Jza(this)}else this.F=(0,g.x)(function(){g.Mo(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Kza(this));a(c);Jza(this)},this),this.C=g.Ko((0,g.x)(function(){this.F()},this),100)};
g.k.yG=function(a,b,c){Eza(this.L,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.mq(d),b(new chrome.cast.DialLaunchResponse(!1))):this.xt(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.xt(b,c)},this))};g.t(C7,y7);C7.prototype.stop=function(){this.Ee()};
C7.prototype.tv=function(){};
C7.prototype.Bk=function(){g.Mo(this.o);this.o=NaN;var a=l6(this.L.xe(),this.u.label);a?this.mq(a):this.Ee(Error("No such screen"))};
C7.prototype.X=function(){g.Mo(this.o);this.o=NaN;y7.prototype.X.call(this)};g.t(D7,g.N);g.k=D7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.CM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.CB,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.TK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),rza(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.MD,this)),this.A=Mza(this),chrome.cast.setCustomReceivers(this.A,g.Ja,(0,g.x)(function(h){this.lc("Failed to set initial custom receivers: "+g.Lk(h))},this)),this.S("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(h){this.lc("Failed to initialize API: "+g.Lk(h));
b(!1)},this))};
g.k.xO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=l6(this.u.xe(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Lza(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ja,(0,g.x)(function(e){this.lc("Failed to set initial custom receivers: "+g.Lk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.vv(b)}else E7("setConnectedScreenStatus: no screen.")};
g.k.yO=function(a){this.ha()?this.lc("Setting connection data on disposed cast v2"):this.o?this.o.Bk(a):this.lc("Setting connection data without a session")};
g.k.uP=function(){this.ha()?this.lc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.CB,this),(0,g.x)(this.XM,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.MD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=oza,b=g.Ia("yt.mdx.remote.debug.handlers_");g.jb(b||[],a);g.Le(this.o);g.N.prototype.X.call(this)};
g.k.lc=function(a){i7("Controller",a)};
g.k.EB=function(a,b){this.o==a&&(b||G7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.yM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.lc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.lc("Stopping receiver w/o session: "+a.friendlyName)}else this.lc("onReceiverAction_ called without receiver.")};
g.k.TK=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.lc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.lc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return E7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.lc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.yG,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.xt,b))};
g.k.CB=function(a){if(!this.ha()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.lc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=l6(this.u.xe(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Le(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.EB,this,this.o)),this.o.Bk(null));this.o.tv(a)}}};
g.k.tP=function(){return this.o?this.o.ND():null};
g.k.XM=function(a){this.ha()||(this.lc("Failed to estabilish a session: "+g.Lk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.k.CM=function(a){E7("Receiver availability updated: "+a);if(!this.ha()){var b=F7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.S("yt-remote-cast2-availability-change",F7(this))}};
g.k.MD=function(){this.ha()||(this.A=Mza(this),E7("Updating custom receivers: "+g.Lk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ja,(0,g.x)(function(){this.lc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.yO;D7.prototype.setConnectedScreenStatus=D7.prototype.xO;D7.prototype.stopSession=D7.prototype.uP;D7.prototype.getCastSession=D7.prototype.tP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.k=R7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Zf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.L=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.ob=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+T7(this):this.I};
g.k.clone=function(){return new R7(X7(this))};g.t(Z7,g.N);g.k=Z7.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ob()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.S("remotePlayerChange")}else a8(this,g.Ra(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.S("remotePlayerChange")}else a8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.lc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.lc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Ra(this.setVolume,a,b))};
g.k.ID=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Lk(b.style),g.Ub(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Ra(this.ID,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Ra(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Lk(h));d8(this,"setPlaylist",m);d||b8(this,l)};
g.k.uq=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Ra(this.uq,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Ra(this.nextVideo,a,b))};
g.k.Mx=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Mx)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.X=function(){Zza(this);this.B=null;this.C.clear();Y7(this,null);g.N.prototype.X.call(this)};
g.k.hw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.fb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.vM=function(a,b){this.S(a,b)};
g.k.CK=function(a){if(!a)this.Sm(null),Y7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.k.Sm=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),$za(this),this.S("remotePlayerChange")};
g.k.BK=function(a){a?($za(this),this.S("remotePlayerChange")):this.Sm(null)};
g.k.Nv=function(){d8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.MK=function(){var a=Wza();a&&Y7(this,a)};
g.k.lc=function(a){i7("CP",a)};g.t(f8,g.N);g.k=f8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.gb.listId=c);this.gb.videoId=d;this.gb.index=h||0;this.gb.state=3;U7(this.gb,m);this.B="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Lk(l));this.o.connect({method:"setPlaylist",
params:g.Lk(l)},a,mya())}else g8("Connecting without params"),this.o.connect({},a,mya());bAa(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),h8(this,3));g.N.prototype.dispose.call(this)};
g.k.X=function(){i8(this);k8(this);j8(this);g.Mo(this.G);this.G=NaN;g.Mo(this.I);this.I=NaN;this.A=null;g.hp(this.T);this.T.length=0;this.o.dispose();g.N.prototype.X.call(this);this.B=this.F=this.u=this.gb=this.o=null};
g.k.OF=function(){this.bk(2)};
g.k.GK=function(){g8("Channel opened");this.R&&(this.R=!1,j8(this),this.N=g.Ko((0,g.x)(function(){g8("Timing out waiting for a screen.");this.bk(1)},this),15E3));
qya(lza(this.o),this.V)};
g.k.DK=function(){g8("Channel closed");isNaN(this.C)?q6(!0):q6();this.dispose()};
g.k.EK=function(a){q6();isNaN(this.hm())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,g8("Channel error: "+a+" with reconnection in "+this.hm()+" ms"),h8(this,2))};
g.k.FK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Lk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Ic)(a,function(c){return new e6(c)});
a=!!g.bb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
eAa(this,a);break;case "loungeScreenDisconnected":g.kb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
eAa(this,!1);break;case "remoteConnected":var b=new e6(x6(a.params.device));g.bb(this.u,function(c){return b?c.id==b.id:!1})||Xxa(this.u,b);
break;case "remoteDisconnected":b=new e6(x6(a.params.device));g.kb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":gAa(this,a);break;case "nowPlaying":iAa(this,a);break;case "onStateChange":hAa(this,a);break;case "onAdStateChange":jAa(this,a);break;case "onVolumeChanged":kAa(this,a);break;case "onSubtitlesTrackChanged":fAa(this,a);break;case "nowAutoplaying":lAa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":mAa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.k.lO=function(){if(this.A){var a=this.A;this.A=null;this.gb.videoId!=a&&l8(this,"getNowPlaying")}};
g.k.FF=function(){var a=3;this.ha()||(a=0,isNaN(this.hm())?d7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.bk=function(a){g8("Disconnecting with "+a);i8(this);this.S("beforeDisconnect",a);1==a&&q6();mza(this.o,a);this.dispose()};
g.k.DF=function(){var a=this.gb;this.A&&(a=this.gb.clone(),W7(a,this.A,a.index));return X7(a)};
g.k.zO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.gb.videoId&&(this.A=b.videoId,g.Mo(this.G),this.G=g.Ko((0,g.x)(this.lO,this),5E3));var c=[];this.gb.listId==b.listId&&this.gb.videoId==b.videoId&&this.gb.index==b.index||c.push("remoteQueueChange");this.gb.playerState==b.playerState&&this.gb.volume==b.volume&&this.gb.muted==b.muted&&V7(this.gb)==V7(b)&&g.Lk(this.gb.o)==g.Lk(b.o)||c.push("remotePlayerChange");this.gb.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.vy=function(){var a=this.o.F.id,b=g.bb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.hm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.C)():NaN};
g.k.sF=function(){return this.B||"UNSUPPORTED"};
g.k.tF=function(){return this.F||""};
g.k.mP=function(){if(!isNaN(this.hm())){var a=this.o.u;g.un(a.o);a.start()}};
g.k.tO=function(a,b){l8(this,a,b);dAa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.ki;f8.prototype.getProxyState=f8.prototype.FF;f8.prototype.disconnect=f8.prototype.bk;f8.prototype.getPlayerContextData=f8.prototype.DF;f8.prototype.setPlayerContextData=f8.prototype.zO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.vy;f8.prototype.getReconnectTimeout=f8.prototype.hm;f8.prototype.getAutoplayMode=f8.prototype.sF;f8.prototype.getAutoplayVideoId=f8.prototype.tF;f8.prototype.reconnect=f8.prototype.mP;
f8.prototype.sendMessage=f8.prototype.tO;g.t(m8,m7);g.k=m8.prototype;g.k.xe=function(a){return this.Jd.$_gs(a)};
g.k.contains=function(a){return!!this.Jd.$_c(a)};
g.k.get=function(a){return this.Jd.$_g(a)};
g.k.start=function(){this.Jd.$_st()};
g.k.add=function(a,b,c){this.Jd.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Jd.$_r(a,b,c)};
g.k.Yq=function(a,b,c,d){this.Jd.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Jd.$_ubk(this.o[a]);this.o.length=0;this.Jd=null;m7.prototype.X.call(this)};
g.k.qP=function(){this.S("screenChange")};
g.k.YL=function(){this.S("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.rP;v7.prototype.$_gsppc=v7.prototype.LD;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Yq;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.xe;v7.prototype.$_gos=v7.prototype.KD;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.ki;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.t(G8,g.z);g.k=G8.prototype;g.k.X=function(){g.z.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.Ya;a.unsubscribe("proxyStateChange",this.yB,this);a.unsubscribe("remotePlayerChange",this.Ym,this);a.unsubscribe("remoteQueueChange",this.nq,this);a.unsubscribe("previousNextChange",this.uB,this);a.unsubscribe("nowAutoplaying",this.qB,this);a.unsubscribe("autoplayDismissed",this.PA,this);this.Ya=this.module=null};
g.k.Tz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ya.o)if(I8(this)){if(!$7(this.Ya).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":$7(this.Ya).ob()?this.Ya.pause():this.Ya.play();break;case "control_play":this.Ya.play();break;case "control_pause":this.Ya.pause();break;case "control_seek":this.F.Cz(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();K8(this,0===c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.AK=function(a){this.G.LF(a)};
g.k.VO=function(a){this.Tz("control_subtitles_set_track",g.Nb(a)?null:a)};
g.k.RC=function(){var a=this.H.getOption("captions","track");g.Nb(a)||J8(this,a)};
g.k.Zb=function(a){this.module.Zb(a,this.H.getVideoData().lengthSeconds)};
g.k.eB=function(a){if(I8(this)){this.Ya.unsubscribe("remotePlayerChange",this.Ym,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.Ya);if(b!==c.volume||a!==c.muted)this.Ya.setVolume(b,a),this.I.start();this.Ya.subscribe("remotePlayerChange",this.Ym,this)}};
g.k.vL=function(){g.Nb(this.A)||yAa(this,this.A);this.B=!1};
g.k.yB=function(a,b){this.u.stop();2===b&&this.PC()};
g.k.Ym=function(){if(I8(this)){this.o.stop();var a=$7(this.Ya);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.hd=1;break;case 1082:case 1083:this.module.hd=0;break;default:this.module.hd=-1}switch(a.playerState){case 1081:case 1:H8(this,new g.wC(8));this.OC();break;case 1085:case 3:H8(this,new g.wC(9));break;case 1083:case 0:H8(this,new g.wC(2));this.F.stop();this.Zb(this.H.getVideoData().lengthSeconds);break;case 1084:H8(this,new g.wC(4));break;case 2:H8(this,new g.wC(4));
this.Zb(V7(a));break;case -1:H8(this,new g.wC(64));break;case -1E3:H8(this,new g.wC(128,{errorCode:"mdx.remoteerror",errorMessage:"\u6b64\u89c6\u9891\u65e0\u6cd5\u8fdc\u7a0b\u64ad\u653e\u3002"}))}a=$7(this.Ya).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,yAa(this,a));a=$7(this.Ya);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.vD()}else xAa(this)};
g.k.uB=function(){this.H.S("mdxpreviousnextchange")};
g.k.nq=function(){I8(this)||xAa(this)};
g.k.qB=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.PA=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){I8(this)&&this.Ya.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===$7(this.Ya).playerState?K8(this,a):b&&this.Ya.seekTo(a)};
g.k.vD=function(){if(I8(this)){var a=$7(this.Ya);this.events.nb(this.L);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.L=this.events.M(this.H,"onVolumeChange",this.eB)}};
g.k.OC=function(){this.o.stop();if(!this.Ya.ha()){var a=$7(this.Ya);a.ob()&&H8(this,new g.wC(8));this.Zb(V7(a));this.o.start()}};
g.k.PC=function(){this.u.stop();this.o.stop();var a=this.Ya.B.getReconnectTimeout();2==this.Ya.o&&!isNaN(a)&&this.u.start()};g.t(L8,g.T);L8.prototype.fc=function(){this.o.show()};
L8.prototype.Ta=function(){this.o.hide()};
L8.prototype.u=function(){g.SN("https://support.google.com/youtube/answer/7640706")};
L8.prototype.A=function(){d6("mdx-manual-pairing-popup-ok");this.Ta()};g.t(M8,g.T);M8.prototype.fc=function(){this.o.show()};
M8.prototype.Ta=function(){this.o.hide()};
M8.prototype.u=function(){d6("mdx-privacy-popup-cancel");this.Ta()};
M8.prototype.A=function(){d6("mdx-privacy-popup-confirm");this.Ta()};g.t(N8,g.T);N8.prototype.u=function(a){AAa(this,a.state)};g.t(O8,g.gR);O8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.si=g.zb(a,this.o,this),g.iR(this,(0,g.Ic)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Lb(this.o(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.o=function(a){return a.key};
O8.prototype.Ef=function(a){return"cast-selector-receiver"===a?"\u6295\u5c04\u2026":this.si[a].name};
O8.prototype.yd=function(a){g.gR.prototype.yd.call(this,a);this.H.setOption("remote","currentReceiver",this.si[a]);this.Na.Ta()};g.t(P8,g.rN);g.k=P8.prototype;
g.k.create=function(){rAa(g.ty(this.player.O()));this.subscriptions.push(g.Ro("yt-remote-before-disconnect",this.yK,this));this.subscriptions.push(g.Ro("yt-remote-connection-change",this.DM,this));this.subscriptions.push(g.Ro("yt-remote-receiver-availability-change",this.wB,this));this.subscriptions.push(g.Ro("yt-remote-auto-connect",this.BM,this));this.subscriptions.push(g.Ro("yt-remote-receiver-resumed",this.AM,this));this.subscriptions.push(g.Ro("mdx-privacy-popup-confirm",this.YN,this));this.subscriptions.push(g.Ro("mdx-privacy-popup-cancel",
this.XN,this));this.subscriptions.push(g.Ro("mdx-manual-pairing-popup-ok",this.QG,this));this.wB()};
g.k.load=function(){this.player.cancelPlayback();g.rN.prototype.load.call(this);this.re=new G8(this,this.player,this.Ya);var a=(a=wAa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!==a&&this.Zb(a);zAa(this,this.Rb,this.Rb);g.AT(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.Ch=this.Bf;g.Me(this.re,this.Ya);this.Ya=this.re=null;g.rN.prototype.unload.call(this);g.AT(this.player.app,5);Q8(this)};
g.k.X=function(){g.So(this.subscriptions);g.rN.prototype.X.call(this)};
g.k.og=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.re.Tz.apply(this.re,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.hd};
g.k.HF=function(){return this.loaded?this.re.suggestion:null};
g.k.Zf=function(){return this.Ya?$7(this.Ya).Zf:!1};
g.k.hasNext=function(){return this.Ya?$7(this.Ya).hasNext:!1};
g.k.Zb=function(a,b){this.oz=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.oz};
g.k.getProgressState=function(){var a=$7(this.Ya),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.gd():!a.isAdPlaying()&&this.player.gd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+T7(a):a.B,isAtLiveHead:1>=(a.A?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.A?a.u+T7(a):a.u,seekableStart:0<a.C?a.C+
T7(a):a.C}};
g.k.nextVideo=function(){this.Ya&&this.Ya.nextVideo()};
g.k.uq=function(){this.Ya&&this.Ya.uq()};
g.k.yK=function(a){1===a&&(this.Pu=this.Ya?$7(this.Ya):null)};
g.k.DM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.Ch;this.loaded&&this.unload();this.Ya=a;this.Pu=null;b.key!==this.Bf.key&&(this.Ch=b,this.load())}else g.Le(this.Ya),this.Ya=null,this.loaded&&(this.unload(),(a=this.Pu)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.wB=function(){this.si=[this.Bf].concat(tAa());var a=y8()||this.Bf;R8(this,a);this.player.sa("onMdxReceiversChange")};
g.k.BM=function(){var a=y8();R8(this,a)};
g.k.AM=function(){this.Ch=y8()};
g.k.YN=function(){this.Zm=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.k.XN=function(){this.Zm=!1;Q8(this);R8(this,this.Bf);this.Ch=this.Bf;E8=!1;F8=null;this.player.playVideo()};
g.k.QG=function(){this.tp=!0;Q8(this);g.Ts("yt-remote-manual-pairing-warning-shown",!0,2592E3);E8=!1;F8&&A8(F8,1);F8=null};
g.k.bd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.si;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?P7():R8(this,b)),this.loaded?this.Ch:this.Bf;case "quickCast":return 2===this.si.length&&"cast-selector-receiver"===this.si[1].key?(b&&P7(),!0):!1}};
g.k.Nv=function(){this.Ya.Nv()};
g.k.Mf=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.GN.remote=P8;})(_yt_player);
